In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import time
import matplotlib.pyplot as plt
from torchvision import datasets, transforms
from bound_propagation import BoundModelFactory, HyperRectangle
from tqdm import tqdm

In [3]:
# !pip3 install bound-propagation

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available()  else "cpu")
batch_size = 64

In [5]:
np.random.seed(42)
torch.manual_seed(42)

In [6]:
## Dataloaders - No normalization for IBP
train_dataset = datasets.MNIST('mnist_data/', train=True, download=True,
                              transform=transforms.Compose([transforms.ToTensor()]))
test_dataset = datasets.MNIST('mnist_data/', train=False, download=True,
                             transform=transforms.Compose([transforms.ToTensor()]))

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [7]:
class Net(nn.Module):
  def __init__(self, hidden_size=50):
    super(Net, self).__init__()
    self.fc1 = nn.Linear(28*28, hidden_size)
    self.fc2 = nn.Linear(hidden_size, hidden_size)
    self.fc3 = nn.Linear(hidden_size, hidden_size)
    self.fc4 = nn.Linear(hidden_size, 10) # Output layer

  def forward(self, x):
    x = x.view((-1, 28*28))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = F.relu(self.fc3(x))
    x = self.fc4(x)
    return x

In [8]:
model = Net().to(device)
model.train()

Net(
  (fc1): Linear(in_features=784, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=50, bias=True)
  (fc3): Linear(in_features=50, out_features=50, bias=True)
  (fc4): Linear(in_features=50, out_features=10, bias=True)
)

In [9]:
def compute_logits_worst_case(model, x, y, eps):
    n = x.size(0)
    flat_x = x.reshape(n, -1)

    # Define perturbed input range [x - eps, x + eps], clamped to valid pixel range
    lower = torch.clamp(flat_x - eps, 0.0, 1.0)
    upper = torch.clamp(flat_x + eps, 0.0, 1.0)
    bounds = HyperRectangle(lower, upper)

    # Reconstruct the sequential feedforward network
    layers = [
        model.fc1, nn.ReLU(),
        model.fc2, nn.ReLU(),
        model.fc3, nn.ReLU(),
        model.fc4
    ]
    sequential_net = nn.Sequential(*layers)

    # Initialize bounded model via factory
    bounded_model = BoundModelFactory().build(sequential_net)

    # Propagate bounds to compute logits interval
    logits_interval = bounded_model.ibp(bounds)
    lo, hi = logits_interval.lower, logits_interval.upper

    # Select lower bounds for true class, upper for all others
    idx = torch.arange(n)
    selector = torch.ones_like(lo, dtype=torch.bool)
    selector[idx, y] = False
    combined_logits = torch.where(selector, hi, lo)

    # Compute cross-entropy over worst-case logits
    loss = F.cross_entropy(combined_logits, y)
    return loss

### Part A

In [14]:
def train_ibp(model, train_loader, epochs=20, max_eps=0.1, device='cuda'):
    model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    log = {'loss': [], 'std_loss': [], 'rob_loss': []}

    print(f"Starting IBP training for {epochs} epochs (target ε={max_eps})")

    for ep in range(epochs):
        model.train()
        total_loss = total_std = total_rob = 0.0

        # Linear schedules
        kappa = 1.0 - 0.5 * (ep / epochs)
        eps = max_eps * (ep / epochs)

        for images, labels in tqdm(train_loader, desc=f"Epoch {ep+1}/{epochs}"):
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()

            # Standard CE
            logits = model(images)
            loss_std = F.cross_entropy(logits, labels)

            # Robust CE via IBP
            loss_rob = compute_logits_worst_case(model, images, labels, eps)

            # Combined objective
            loss = kappa * loss_std + (1 - kappa) * loss_rob
            loss.backward()
            optimizer.step()

        model.eval()
        tot_val, tot_acc = 0.0, 0.0
        val_loss = 0.0
        for batch_idx, (images, labels) in enumerate(train_loader):
            images = images.view((-1, 28*28))
            images, labels = images.to(device), labels.to(device)
            with torch.no_grad():
                logits = model(images)
                ce_loss = nn.CrossEntropyLoss()(logits, labels)
                rb_loss = compute_logits_worst_case(model, images, labels, eps)
                loss = kappa * ce_loss + (1 - kappa) * rb_loss
                val_loss += loss.item()
                tot_acc += (logits.argmax(dim=1) == labels).sum().item()
                tot_val += labels.size(0)
        val_acc = 100.0 * tot_acc / tot_val

        print(f'Epoch {ep+1}/{epochs}, Loss: {val_loss/len(train_loader):.3f}, Accuracy: {val_acc:.2f}%')

        # print(f"Epoch {ep+1:2d}/{epochs} → Loss={avg_loss:.4f}, Std={avg_std:.4f}, Rob={avg_rob:.4f}")

    return log


# === Example usage ===
start = time.time()
history = train_ibp(model, train_loader, epochs=20, max_eps=0.1, device=device)
ibp_tt = time.time() - start

print(f"\nIBP Training completed in {ibp_tt:.2f}s ({ibp_tt/60:.2f}m)")

Starting IBP training for 20 epochs (target ε=0.1)


Epoch 1/20: 100%|██████████| 938/938 [00:03<00:00, 249.56it/s]


Epoch 1/20, Loss: 0.092, Accuracy: 97.17%


Epoch 2/20:  37%|███▋      | 349/938 [00:01<00:02, 236.45it/s]


KeyboardInterrupt: 

In [ ]:
def train_standard(model, train_loader, epochs=5, lr=1e-3, device='cuda'):
    model.to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    start = time.time()

    for ep in range(epochs):
        model.train()
        total_loss = 0.0

        for images, labels in tqdm(train_loader, desc=f"Epoch {ep+1}/{epochs}"):
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()
            loss = F.cross_entropy(model(images), labels)
            print(model(images))
            print(labels)
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f'Epoch {ep+1}/{epochs}, Loss: {total_loss/len(train_loader):.3f}')

    return time.time() - start


# === Example usage and timing comparison ===
std_model = Net().to(device)
standard_tt = train_standard(std_model, train_loader, epochs=20, lr=1e-3, device=device)

diff = ibp_tt - standard_tt
print(f"\nTraining Time Comparison:")
print(f"  IBP: {ibp_tt:.2f}s ({ibp_tt/60:.2f}m)")
print(f"  Standard: {standard_tt:.2f}s ({standard_tt/60:.2f}m)")


Epoch 1/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.8727e-01, -1.3209e-02,  7.4516e-02,  6.8734e-02, -4.6380e-02,
         -8.8713e-03,  3.1458e-02,  1.1947e-01, -2.2609e-02,  1.0335e-01],
        [ 1.7813e-01, -7.9515e-03,  7.8004e-02,  6.2014e-02, -4.9423e-02,
         -8.9813e-03,  2.4728e-02,  1.1157e-01, -2.9523e-02,  1.0001e-01],
        [ 1.9976e-01, -2.0156e-02,  8.3598e-02,  6.4407e-02, -4.2874e-02,
         -1.3522e-02,  2.8986e-02,  1.1516e-01, -2.9351e-02,  1.0860e-01],
        [ 1.9783e-01, -2.3009e-02,  7.9572e-02,  6.4112e-02, -3.7375e-02,
         -1.0857e-02,  1.6679e-02,  1.0455e-01, -2.4943e-02,  1.0100e-01],
        [ 1.7530e-01, -1.0726e-02,  7.3831e-02,  6.3816e-02, -5.1005e-02,
         -1.0634e-02,  2.2616e-02,  1.1223e-01, -2.9413e-02,  9.8754e-02],
        [ 1.9836e-01, -1.7615e-02,  7.1975e-02,  6.9193e-02, -5.4555e-02,
         -1.7205e-02,  3.5414e-02,  1.2442e-01, -1.9959e-02,  1.0028e-01],
        [ 1.8507e-01, -1.5822e-02,  7.5163e-02,  7.4274e-02, -3.8143e-02,
         -1.3277e-02,  2.5809e-0

Epoch 2/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.8003e-01, -1.6454e-02,  7.7410e-02,  6.8907e-02, -4.5112e-02,
         -7.6172e-03,  2.1761e-02,  1.1471e-01, -3.4400e-02,  1.0899e-01],
        [ 1.8128e-01, -1.7156e-02,  8.5985e-02,  5.3305e-02, -4.3930e-02,
         -8.1810e-03,  5.1797e-03,  9.5363e-02, -2.9028e-02,  1.0637e-01],
        [ 1.8603e-01, -1.2300e-02,  8.1492e-02,  7.3341e-02, -4.2365e-02,
         -1.6173e-02,  3.5726e-02,  1.2062e-01, -3.0421e-02,  9.8150e-02],
        [ 1.7920e-01, -3.4879e-03,  7.8177e-02,  5.4892e-02, -4.7068e-02,
         -8.6806e-03,  1.6145e-02,  1.1378e-01, -2.4439e-02,  1.0053e-01],
        [ 1.8783e-01, -6.7390e-03,  8.0098e-02,  6.2258e-02, -4.7568e-02,
         -1.8790e-02,  2.6519e-02,  1.1195e-01, -3.0692e-02,  9.4290e-02],
        [ 1.7642e-01, -7.1239e-03,  8.2129e-02,  6.4243e-02, -4.4786e-02,
         -2.0632e-03,  2.0326e-02,  1.1555e-01, -4.2912e-02,  1.0034e-01],
        [ 1.8184e-01, -7.3846e-03,  7.9339e-02,  6.5553e-02, -4.1459e-02,
         -1.0178e-02,  1.8438e-0

Epoch 3/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.7415e-01, -1.4649e-02,  8.8979e-02,  4.5998e-02, -3.9137e-02,
         -4.3181e-03,  1.5976e-02,  9.6868e-02, -2.7619e-02,  1.1064e-01],
        [ 1.8296e-01, -1.4223e-02,  9.0465e-02,  7.6516e-02, -3.8747e-02,
         -1.8421e-02,  3.4932e-02,  1.1079e-01, -4.0161e-02,  9.9001e-02],
        [ 1.8233e-01, -7.3503e-03,  8.3013e-02,  6.5837e-02, -4.6936e-02,
         -1.4081e-02,  3.1135e-02,  1.2390e-01, -2.6982e-02,  1.0585e-01],
        [ 1.8141e-01, -1.3216e-04,  8.4699e-02,  6.9627e-02, -4.2041e-02,
         -9.5593e-03,  2.8755e-02,  1.2020e-01, -4.2121e-02,  9.2150e-02],
        [ 1.8659e-01, -7.7623e-03,  7.8652e-02,  7.4318e-02, -4.8963e-02,
         -8.9081e-03,  3.0544e-02,  1.2616e-01, -3.7059e-02,  9.9819e-02],
        [ 1.6779e-01, -9.2893e-03,  8.2625e-02,  6.4122e-02, -5.4869e-02,
         -2.4197e-03,  2.6139e-02,  1.2093e-01, -4.1747e-02,  1.0761e-01],
        [ 1.8363e-01, -2.3016e-02,  8.0554e-02,  6.8498e-02, -4.3781e-02,
         -1.4235e-03,  2.3319e-0

Epoch 4/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 0.1747, -0.0139,  0.0831,  0.0759, -0.0398, -0.0087,  0.0311,  0.1124,
         -0.0472,  0.0965],
        [ 0.1768, -0.0039,  0.0727,  0.0659, -0.0493, -0.0028,  0.0222,  0.1208,
         -0.0356,  0.0927],
        [ 0.1806, -0.0071,  0.0814,  0.0613, -0.0507, -0.0108,  0.0243,  0.1099,
         -0.0305,  0.0944],
        [ 0.2017, -0.0198,  0.0955,  0.0712, -0.0236, -0.0238,  0.0453,  0.1044,
         -0.0410,  0.0890],
        [ 0.1869, -0.0087,  0.0767,  0.0772, -0.0485, -0.0177,  0.0306,  0.1253,
         -0.0240,  0.1089],
        [ 0.1751, -0.0051,  0.0830,  0.0740, -0.0512, -0.0066,  0.0356,  0.1252,
         -0.0454,  0.1014],
        [ 0.1798, -0.0078,  0.0767,  0.0663, -0.0482, -0.0104,  0.0195,  0.1115,
         -0.0336,  0.0927],
        [ 0.1916, -0.0060,  0.0822,  0.0595, -0.0448, -0.0170,  0.0262,  0.1082,
         -0.0260,  0.0965],
        [ 0.1936, -0.0108,  0.0919,  0.0640, -0.0392, -0.0152,  0.0202,  0.1094,
         -0.0407,  0.1009],
        [ 0.1861, -

Epoch 5/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 0.1807, -0.0145,  0.0981,  0.0577, -0.0316, -0.0071,  0.0249,  0.1065,
         -0.0359,  0.1041],
        [ 0.1817, -0.0036,  0.0789,  0.0599, -0.0498, -0.0106,  0.0247,  0.1214,
         -0.0275,  0.1003],
        [ 0.1857, -0.0173,  0.0831,  0.0718, -0.0374, -0.0172,  0.0321,  0.1146,
         -0.0264,  0.1009],
        [ 0.1973, -0.0009,  0.0846,  0.0553, -0.0364, -0.0233,  0.0169,  0.1031,
         -0.0177,  0.0948],
        [ 0.1965, -0.0080,  0.0819,  0.0712, -0.0459, -0.0193,  0.0247,  0.1270,
         -0.0208,  0.1011],
        [ 0.1674, -0.0034,  0.0775,  0.0652, -0.0478, -0.0038,  0.0205,  0.1178,
         -0.0443,  0.0977],
        [ 0.1786, -0.0119,  0.0786,  0.0668, -0.0432, -0.0110,  0.0253,  0.1165,
         -0.0280,  0.1026],
        [ 0.1747, -0.0132,  0.0780,  0.0695, -0.0422, -0.0114,  0.0319,  0.1129,
         -0.0350,  0.1023],
        [ 0.1757, -0.0074,  0.0873,  0.0720, -0.0516, -0.0111,  0.0367,  0.1252,
         -0.0387,  0.1055],
        [ 0.1737, -

Epoch 6/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 0.1726, -0.0141,  0.0801,  0.0625, -0.0511, -0.0062,  0.0205,  0.1127,
         -0.0365,  0.1097],
        [ 0.1765, -0.0089,  0.0829,  0.0643, -0.0505,  0.0048,  0.0186,  0.1206,
         -0.0379,  0.1060],
        [ 0.1865, -0.0133,  0.0749,  0.0737, -0.0415, -0.0115,  0.0335,  0.1186,
         -0.0255,  0.0987],
        [ 0.1743, -0.0076,  0.0729,  0.0682, -0.0443, -0.0105,  0.0249,  0.1202,
         -0.0341,  0.0984],
        [ 0.2043, -0.0126,  0.0799,  0.0636, -0.0405, -0.0251,  0.0308,  0.1174,
         -0.0133,  0.0934],
        [ 0.1838, -0.0058,  0.0737,  0.0712, -0.0423, -0.0108,  0.0258,  0.1201,
         -0.0252,  0.0948],
        [ 0.1763, -0.0095,  0.0776,  0.0698, -0.0401, -0.0091,  0.0269,  0.1186,
         -0.0430,  0.0949],
        [ 0.1817, -0.0131,  0.0823,  0.0623, -0.0472, -0.0108,  0.0223,  0.1153,
         -0.0292,  0.1002],
        [ 0.1735, -0.0091,  0.0763,  0.0707, -0.0399, -0.0099,  0.0260,  0.1169,
         -0.0404,  0.0971],
        [ 0.1839, -

Epoch 7/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.9036e-01, -1.2659e-02,  8.0049e-02,  7.2735e-02, -4.2904e-02,
         -1.2089e-02,  2.4756e-02,  1.1434e-01, -3.5722e-02,  9.7017e-02],
        [ 1.8943e-01, -1.3291e-02,  8.0167e-02,  6.5419e-02, -4.8942e-02,
         -9.2644e-03,  2.0663e-02,  1.0921e-01, -2.7609e-02,  9.7226e-02],
        [ 1.8295e-01, -9.1783e-03,  7.9627e-02,  5.5346e-02, -4.3146e-02,
         -1.2941e-02,  2.6257e-02,  1.1138e-01, -2.2042e-02,  1.0037e-01],
        [ 1.7822e-01, -8.8870e-03,  7.8870e-02,  7.1963e-02, -4.1432e-02,
         -5.0980e-03,  2.6648e-02,  1.1711e-01, -4.3312e-02,  9.2397e-02],
        [ 1.8321e-01, -2.1555e-03,  7.8641e-02,  6.3071e-02, -4.5143e-02,
         -6.1836e-03,  2.1215e-02,  1.1918e-01, -3.6519e-02,  9.3605e-02],
        [ 1.8697e-01, -7.2518e-03,  8.4949e-02,  7.8348e-02, -4.0849e-02,
         -1.3343e-02,  3.4148e-02,  1.2239e-01, -4.0949e-02,  1.0006e-01],
        [ 1.8520e-01, -3.4926e-03,  7.3872e-02,  6.7473e-02, -3.8316e-02,
         -2.0359e-02,  2.7267e-0

Epoch 8/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 0.1908, -0.0149,  0.0816,  0.0672, -0.0437, -0.0072,  0.0229,  0.1081,
         -0.0315,  0.0960],
        [ 0.1827, -0.0139,  0.0822,  0.0619, -0.0454, -0.0078,  0.0309,  0.1118,
         -0.0429,  0.1029],
        [ 0.1740, -0.0066,  0.0748,  0.0672, -0.0482, -0.0023,  0.0254,  0.1216,
         -0.0381,  0.0961],
        [ 0.2006, -0.0097,  0.0870,  0.0732, -0.0365, -0.0257,  0.0384,  0.1121,
         -0.0238,  0.0883],
        [ 0.1958, -0.0148,  0.0786,  0.0659, -0.0428, -0.0122,  0.0153,  0.1118,
         -0.0334,  0.0969],
        [ 0.1737, -0.0042,  0.0856,  0.0721, -0.0497, -0.0030,  0.0249,  0.1265,
         -0.0455,  0.1053],
        [ 0.1855, -0.0092,  0.0748,  0.0580, -0.0516, -0.0070,  0.0220,  0.1119,
         -0.0291,  0.0977],
        [ 0.1838, -0.0036,  0.0854,  0.0694, -0.0471, -0.0134,  0.0269,  0.1186,
         -0.0372,  0.0942],
        [ 0.1849, -0.0154,  0.0867,  0.0792, -0.0294, -0.0216,  0.0344,  0.1146,
         -0.0364,  0.1065],
        [ 0.1943, -

Epoch 9/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.7671e-01, -8.6724e-03,  7.5640e-02,  6.5949e-02, -5.0215e-02,
         -6.2970e-03,  2.0298e-02,  1.1476e-01, -4.2209e-02,  1.0090e-01],
        [ 1.8522e-01, -9.9940e-03,  8.3414e-02,  7.1675e-02, -4.7062e-02,
         -1.0859e-02,  2.7284e-02,  1.1558e-01, -4.0781e-02,  9.8650e-02],
        [ 1.8684e-01, -7.8887e-03,  8.0109e-02,  6.9292e-02, -4.2192e-02,
         -1.4061e-02,  2.7227e-02,  1.1630e-01, -3.0061e-02,  9.3321e-02],
        [ 1.7409e-01, -9.1580e-03,  7.4514e-02,  6.5694e-02, -4.9959e-02,
          1.8662e-03,  1.6016e-02,  1.1566e-01, -3.9315e-02,  9.8244e-02],
        [ 1.7288e-01, -1.4199e-02,  7.9053e-02,  6.8946e-02, -4.1785e-02,
         -1.2094e-02,  3.1275e-02,  1.1523e-01, -3.8341e-02,  1.0665e-01],
        [ 1.8309e-01, -1.1189e-03,  8.4113e-02,  6.7537e-02, -4.7300e-02,
          6.1471e-04,  1.8265e-02,  1.2364e-01, -4.3713e-02,  9.3534e-02],
        [ 1.7755e-01, -3.6755e-03,  8.0837e-02,  6.3501e-02, -4.7160e-02,
         -7.5049e-03,  2.0800e-0

Epoch 10/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 0.1855, -0.0035,  0.0771,  0.0638, -0.0510, -0.0097,  0.0235,  0.1182,
         -0.0280,  0.0927],
        [ 0.1722, -0.0090,  0.0895,  0.0720, -0.0453, -0.0006,  0.0252,  0.1257,
         -0.0495,  0.1104],
        [ 0.1856, -0.0064,  0.0829,  0.0644, -0.0358, -0.0200,  0.0287,  0.1133,
         -0.0247,  0.0949],
        [ 0.1899, -0.0091,  0.0853,  0.0745, -0.0434, -0.0196,  0.0321,  0.1217,
         -0.0368,  0.1028],
        [ 0.1908, -0.0122,  0.0839,  0.0685, -0.0438, -0.0079,  0.0176,  0.1107,
         -0.0367,  0.0966],
        [ 0.1908, -0.0104,  0.0767,  0.0736, -0.0425, -0.0232,  0.0399,  0.1181,
         -0.0334,  0.0952],
        [ 0.1887, -0.0097,  0.0820,  0.0651, -0.0408, -0.0153,  0.0288,  0.1153,
         -0.0327,  0.0976],
        [ 0.1856, -0.0103,  0.0768,  0.0760, -0.0401, -0.0132,  0.0324,  0.1171,
         -0.0330,  0.0900],
        [ 0.1743, -0.0207,  0.0846,  0.0611, -0.0496, -0.0051,  0.0237,  0.1114,
         -0.0346,  0.1083],
        [ 0.1832, -

Epoch 11/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.8170e-01, -1.4105e-02,  9.2378e-02,  7.2111e-02, -3.7555e-02,
         -9.2403e-03,  3.2271e-02,  1.1424e-01, -4.8820e-02,  1.0131e-01],
        [ 1.7416e-01, -1.5078e-02,  7.8023e-02,  7.3385e-02, -3.4734e-02,
         -1.2495e-02,  2.4592e-02,  1.1406e-01, -4.6658e-02,  9.8273e-02],
        [ 1.8958e-01, -1.5563e-02,  7.6286e-02,  6.0742e-02, -4.7383e-02,
         -1.0132e-02,  2.6765e-02,  1.1189e-01, -2.1513e-02,  1.0396e-01],
        [ 2.0338e-01, -1.8131e-02,  6.9405e-02,  6.3773e-02, -4.4699e-02,
         -2.0131e-02,  2.3167e-02,  1.0850e-01, -2.0819e-02,  8.9013e-02],
        [ 1.8267e-01, -1.5405e-02,  7.8509e-02,  7.4082e-02, -3.8624e-02,
         -1.2684e-02,  2.7324e-02,  1.1501e-01, -3.4739e-02,  1.0045e-01],
        [ 1.8253e-01, -1.2448e-02,  7.9435e-02,  6.2589e-02, -4.9813e-02,
         -1.2205e-03,  1.8013e-02,  1.0848e-01, -3.1783e-02,  9.9133e-02],
        [ 2.0074e-01, -2.3831e-02,  7.6533e-02,  5.9876e-02, -4.1764e-02,
         -1.4455e-02,  2.1978e-0

Epoch 12/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.9054e-01, -1.2642e-02,  8.0142e-02,  6.4425e-02, -3.7179e-02,
         -1.7714e-02,  2.5900e-02,  1.1543e-01, -1.4226e-02,  1.0794e-01],
        [ 1.9089e-01, -6.8821e-03,  7.5485e-02,  6.7172e-02, -4.8363e-02,
         -1.4296e-02,  2.4031e-02,  1.1576e-01, -3.0128e-02,  9.8048e-02],
        [ 1.9904e-01, -2.1601e-02,  8.0980e-02,  6.9481e-02, -3.6108e-02,
         -1.8343e-02,  2.5249e-02,  1.1618e-01, -2.4448e-02,  1.0442e-01],
        [ 1.8255e-01, -9.3181e-03,  8.9218e-02,  7.6210e-02, -4.8910e-02,
         -1.5232e-02,  3.8823e-02,  1.2640e-01, -3.3644e-02,  1.0842e-01],
        [ 1.7568e-01, -1.0433e-02,  7.7281e-02,  6.7612e-02, -4.1220e-02,
         -3.2534e-03,  2.4867e-02,  1.1640e-01, -4.0798e-02,  9.6534e-02],
        [ 1.9425e-01, -1.0939e-02,  7.9918e-02,  7.0879e-02, -4.5521e-02,
         -1.7685e-02,  3.7486e-02,  1.2291e-01, -2.0548e-02,  9.6384e-02],
        [ 1.9980e-01, -2.0376e-02,  7.3682e-02,  6.6177e-02, -4.6952e-02,
         -1.3843e-02,  2.1228e-0

Epoch 13/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.7080e-01, -7.4970e-03,  7.9222e-02,  6.4915e-02, -4.9833e-02,
          4.9136e-03,  2.0521e-02,  1.1495e-01, -4.6154e-02,  9.5511e-02],
        [ 1.8888e-01, -4.6677e-03,  8.2598e-02,  6.2415e-02, -4.0308e-02,
         -1.1500e-02,  2.0135e-02,  1.0743e-01, -3.5390e-02,  9.7355e-02],
        [ 1.9892e-01, -9.5460e-03,  7.5776e-02,  6.5908e-02, -4.0846e-02,
         -2.1682e-02,  2.5623e-02,  1.0803e-01, -2.0785e-02,  8.6263e-02],
        [ 1.8032e-01, -1.1049e-02,  7.9223e-02,  6.1086e-02, -4.8164e-02,
         -1.0960e-02,  1.7124e-02,  1.1074e-01, -2.7117e-02,  9.7445e-02],
        [ 1.9331e-01, -4.2148e-03,  7.5998e-02,  6.8964e-02, -4.7946e-02,
         -1.8580e-02,  2.6988e-02,  1.1739e-01, -3.1503e-02,  8.9832e-02],
        [ 1.8656e-01, -1.6530e-02,  7.6533e-02,  6.6490e-02, -4.3966e-02,
         -1.4902e-02,  2.2404e-02,  9.9763e-02, -3.2090e-02,  9.9108e-02],
        [ 1.8952e-01,  1.3430e-03,  8.8434e-02,  7.0993e-02, -4.9212e-02,
         -7.5458e-03,  2.8467e-0

Epoch 14/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 0.1873, -0.0157,  0.0824,  0.0534, -0.0516,  0.0024,  0.0094,  0.1172,
         -0.0406,  0.1061],
        [ 0.1782, -0.0094,  0.0760,  0.0738, -0.0452, -0.0101,  0.0257,  0.1229,
         -0.0350,  0.1037],
        [ 0.1838, -0.0085,  0.0720,  0.0708, -0.0505, -0.0084,  0.0295,  0.1159,
         -0.0271,  0.0927],
        [ 0.1833, -0.0051,  0.0831,  0.0696, -0.0470, -0.0074,  0.0285,  0.1224,
         -0.0397,  0.0989],
        [ 0.1977, -0.0211,  0.0774,  0.0698, -0.0478, -0.0053,  0.0201,  0.1149,
         -0.0335,  0.1007],
        [ 0.2015, -0.0105,  0.0812,  0.0720, -0.0378, -0.0189,  0.0278,  0.1156,
         -0.0183,  0.0931],
        [ 0.1813, -0.0166,  0.0727,  0.0663, -0.0445, -0.0070,  0.0214,  0.1140,
         -0.0427,  0.1047],
        [ 0.1748, -0.0048,  0.0822,  0.0608, -0.0490, -0.0069,  0.0222,  0.1117,
         -0.0374,  0.0943],
        [ 0.1957, -0.0064,  0.0769,  0.0688, -0.0371, -0.0166,  0.0204,  0.1068,
         -0.0293,  0.0890],
        [ 0.1857, -

Epoch 15/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 0.1819, -0.0099,  0.0878,  0.0635, -0.0406, -0.0079,  0.0242,  0.1100,
         -0.0471,  0.0984],
        [ 0.2140, -0.0047,  0.0841,  0.0548, -0.0309, -0.0230,  0.0247,  0.1090,
         -0.0034,  0.0937],
        [ 0.2037, -0.0149,  0.0793,  0.0639, -0.0488, -0.0142,  0.0226,  0.1201,
         -0.0266,  0.0905],
        [ 0.1883, -0.0129,  0.0834,  0.0696, -0.0271, -0.0126,  0.0204,  0.1119,
         -0.0318,  0.0973],
        [ 0.1749, -0.0048,  0.0750,  0.0675, -0.0468, -0.0066,  0.0251,  0.1226,
         -0.0403,  0.0977],
        [ 0.1807, -0.0100,  0.0723,  0.0587, -0.0505, -0.0127,  0.0186,  0.1078,
         -0.0316,  0.0957],
        [ 0.1906, -0.0181,  0.0770,  0.0663, -0.0473, -0.0163,  0.0222,  0.1143,
         -0.0230,  0.1039],
        [ 0.1976, -0.0042,  0.0811,  0.0723, -0.0448, -0.0203,  0.0320,  0.1138,
         -0.0218,  0.0933],
        [ 0.1815, -0.0117,  0.0765,  0.0701, -0.0433, -0.0088,  0.0216,  0.1195,
         -0.0363,  0.1050],
        [ 0.1800, -

Epoch 16/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.8331e-01, -9.8524e-03,  7.3637e-02,  6.7227e-02, -4.9853e-02,
         -7.0528e-03,  2.2711e-02,  1.1831e-01, -3.4950e-02,  9.5282e-02],
        [ 1.9185e-01, -1.7188e-02,  7.8021e-02,  6.5128e-02, -4.8421e-02,
         -7.9169e-03,  2.1501e-02,  1.1510e-01, -2.8571e-02,  1.0428e-01],
        [ 1.8322e-01, -1.1231e-02,  7.1451e-02,  5.7963e-02, -5.5805e-02,
         -1.4548e-03,  1.7204e-02,  1.1209e-01, -2.0540e-02,  1.0318e-01],
        [ 1.9069e-01,  2.1050e-03,  8.6767e-02,  6.2166e-02, -3.6993e-02,
         -1.5501e-02,  2.5832e-02,  1.0460e-01, -2.8329e-02,  9.1703e-02],
        [ 1.9350e-01, -1.1824e-02,  7.9857e-02,  7.3904e-02, -4.9974e-02,
         -1.4173e-02,  2.9940e-02,  1.1825e-01, -2.1868e-02,  1.0237e-01],
        [ 1.8437e-01, -1.1666e-02,  7.7140e-02,  6.5022e-02, -5.0615e-02,
         -4.1297e-04,  1.3029e-02,  1.1697e-01, -4.2414e-02,  1.0028e-01],
        [ 1.8172e-01, -6.2436e-03,  7.8901e-02,  7.2289e-02, -4.4455e-02,
         -6.2268e-03,  2.7179e-0

Epoch 17/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.8586e-01, -1.2846e-02,  8.4504e-02,  6.4282e-02, -3.9918e-02,
         -1.4701e-02,  2.0744e-02,  1.0596e-01, -3.1846e-02,  9.6607e-02],
        [ 1.8967e-01, -1.4350e-02,  8.0195e-02,  6.1408e-02, -5.1743e-02,
         -4.0234e-03,  1.6431e-02,  1.1055e-01, -2.8146e-02,  1.0368e-01],
        [ 1.7225e-01, -1.2160e-02,  7.4821e-02,  6.7449e-02, -5.4285e-02,
         -4.7347e-03,  1.4834e-02,  1.1852e-01, -3.5047e-02,  1.0887e-01],
        [ 1.9071e-01, -1.1208e-02,  8.7911e-02,  6.8579e-02, -5.1460e-02,
         -4.7472e-03,  2.6507e-02,  1.2298e-01, -3.7606e-02,  1.0073e-01],
        [ 1.7368e-01, -9.5444e-03,  7.3531e-02,  6.9466e-02, -4.3949e-02,
         -4.6209e-03,  2.5595e-02,  1.1893e-01, -3.5059e-02,  1.0106e-01],
        [ 1.7326e-01, -6.9385e-03,  7.8822e-02,  6.3713e-02, -5.5048e-02,
         -5.9444e-03,  2.5989e-02,  1.1899e-01, -3.1311e-02,  1.0300e-01],
        [ 1.9658e-01, -1.4576e-02,  8.7045e-02,  7.1212e-02, -3.8497e-02,
         -2.0650e-02,  2.6263e-0

Epoch 18/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 1.9777e-01, -6.0303e-03,  7.9131e-02,  7.6679e-02, -3.8129e-02,
         -2.7745e-02,  3.8166e-02,  1.1295e-01, -1.9209e-02,  9.2705e-02],
        [ 1.8373e-01, -7.5342e-03,  8.7106e-02,  7.1859e-02, -4.6252e-02,
         -7.7932e-03,  2.8413e-02,  1.2224e-01, -3.7227e-02,  9.9941e-02],
        [ 1.7783e-01, -1.7095e-03,  6.9412e-02,  6.7520e-02, -4.8524e-02,
         -7.4135e-03,  2.0731e-02,  1.2217e-01, -3.3109e-02,  9.1160e-02],
        [ 1.7512e-01, -2.7803e-03,  7.1697e-02,  6.5192e-02, -5.1262e-02,
         -7.4546e-03,  2.6302e-02,  1.2228e-01, -2.9952e-02,  9.6863e-02],
        [ 1.8481e-01, -1.1815e-02,  7.8774e-02,  7.3698e-02, -3.7941e-02,
         -1.2377e-02,  2.2496e-02,  1.0765e-01, -4.3394e-02,  9.0711e-02],
        [ 1.9741e-01, -1.4503e-02,  6.8170e-02,  7.0523e-02, -3.9033e-02,
         -1.5710e-02,  2.0753e-02,  1.0395e-01, -1.3276e-02,  9.5396e-02],
        [ 1.8257e-01, -2.9021e-03,  8.7319e-02,  5.2602e-02, -3.7374e-02,
         -1.6954e-02,  3.2253e-0

Epoch 19/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 0.1973, -0.0027,  0.0873,  0.0500, -0.0400, -0.0152,  0.0087,  0.1037,
         -0.0277,  0.0955],
        [ 0.1765, -0.0211,  0.0935,  0.0741, -0.0277, -0.0134,  0.0365,  0.1075,
         -0.0480,  0.1030],
        [ 0.1964, -0.0159,  0.0857,  0.0633, -0.0413, -0.0087,  0.0177,  0.1089,
         -0.0229,  0.1015],
        [ 0.2004, -0.0120,  0.0763,  0.0676, -0.0430, -0.0121,  0.0209,  0.1059,
         -0.0285,  0.0955],
        [ 0.1851, -0.0081,  0.0740,  0.0675, -0.0428, -0.0102,  0.0205,  0.1145,
         -0.0237,  0.0988],
        [ 0.1821, -0.0089,  0.0841,  0.0707, -0.0460, -0.0084,  0.0225,  0.1205,
         -0.0410,  0.1035],
        [ 0.1933, -0.0185,  0.0752,  0.0552, -0.0492, -0.0141,  0.0207,  0.1060,
         -0.0182,  0.1018],
        [ 0.1873, -0.0148,  0.0793,  0.0666, -0.0468, -0.0006,  0.0205,  0.1099,
         -0.0367,  0.0956],
        [ 0.1755, -0.0091,  0.0842,  0.0651, -0.0461, -0.0081,  0.0253,  0.1162,
         -0.0394,  0.1069],
        [ 0.1962, -

Epoch 20/20:   0%|          | 0/938 [00:00<?, ?it/s]

tensor([[ 1.9875e-01, -5.3896e-03,  7.9487e-02,  6.7450e-02, -4.5717e-02,
         -2.2313e-02,  2.8945e-02,  1.1908e-01, -2.5261e-02,  9.2952e-02],
        [ 1.8141e-01, -1.2143e-02,  8.4796e-02,  7.3964e-02, -4.0838e-02,
         -7.7666e-03,  3.1273e-02,  1.1627e-01, -3.9546e-02,  1.0001e-01],
        [ 2.0997e-01, -1.7757e-02,  8.0429e-02,  6.8739e-02, -3.7089e-02,
         -2.2383e-02,  3.5236e-02,  1.1624e-01, -1.8644e-02,  8.4766e-02],
        [ 1.9524e-01, -1.0439e-02,  7.6063e-02,  6.9209e-02, -4.7070e-02,
         -1.4880e-02,  3.2249e-02,  1.1576e-01, -3.2883e-02,  8.9298e-02],
        [ 1.7742e-01, -5.6965e-03,  8.3281e-02,  6.2203e-02, -5.5449e-02,
          7.8577e-03,  1.3789e-02,  1.2179e-01, -3.6246e-02,  1.0437e-01],
        [ 1.8249e-01, -5.3086e-03,  7.4677e-02,  7.4455e-02, -5.1209e-02,
          1.7307e-04,  2.4020e-02,  1.2534e-01, -4.2653e-02,  9.6245e-02],
        [ 1.9175e-01, -1.1841e-02,  7.5908e-02,  6.8136e-02, -4.7128e-02,
         -1.5551e-02,  2.0826e-0

NameError: name 'ibp_tt' is not defined

In [10]:
def pgd_attack(model, x, y, eps: float = 0.1, step_size: float = 0.01, steps: int = 40):
    model.eval()
    batch_size = x.size(0)

    # Flatten input for consistent gradient operations
    x_orig = x.view(batch_size, -1)
    x_adv = x_orig.clone().detach()

    for _ in range(steps):
        x_adv.requires_grad_(True)

        logits = model(x_adv.view_as(x))
        loss = F.cross_entropy(logits, y)

        # Compute gradients w.r.t input
        grad = torch.autograd.grad(loss, x_adv)[0]
        x_adv = x_adv.detach() + step_size * grad.sign()

        # Project perturbation back to ε-ball
        delta = torch.clamp(x_adv - x_orig, min=-eps, max=eps)
        x_adv = torch.clamp(x_orig + delta, 0.0, 1.0)

    # Reshape back to original input dimensions
    return x_adv.view_as(x)


In [13]:
def evaluate_accuracy_and_robustness(model, loader, eps=0.1, device="cuda"):
    model.eval()
    correct_clean = correct_adv = total = 0

    for x, y in tqdm(loader, desc="Evaluating"):
        x, y = x.to(device), y.to(device)
        total += y.size(0)

        with torch.no_grad():
            clean_pred = model(x).argmax(1)
            correct_clean += (clean_pred == y).sum().item()

        x_adv = pgd_attack(model, x, y, eps=eps, step_size=0.01, steps=40)
        with torch.no_grad():
            adv_pred = model(x_adv).argmax(1)
            correct_adv += (adv_pred == y).sum().item()

    std_acc = 100 * correct_clean / total
    rob_acc = 100 * correct_adv / total
    return std_acc, rob_acc


# === Evaluate both models ===
ibp_std_acc, ibp_rob_acc = evaluate_accuracy_and_robustness(model, test_loader, eps=0.1, device=device)
std_std_acc, std_rob_acc = evaluate_accuracy_and_robustness(std_model, test_loader, eps=0.1, device=device)

print("\nResults Summary")
print("-" * 50)
print(f"IBP Model     - Standard: {ibp_std_acc:.2f}% | Robust: {ibp_rob_acc:.2f}%")
print(f"Standard Model- Standard: {std_std_acc:.2f}% | Robust: {std_rob_acc:.2f}%")

Evaluating: 100%|██████████| 157/157 [00:02<00:00, 56.55it/s]


Results Summary
--------------------------------------------------
IBP Model     - Standard: 95.24% | Robust: 83.81%
Standard Model- Standard: 97.22% | Robust: 1.03%


### Part B

In [ ]:
def verify_robustness_single_image(model, x, y, eps):
    x_flat = x.view(1, -1)
    lower_bound = torch.clamp(x_flat - eps, 0.0, 1.0)
    upper_bound = torch.clamp(x_flat + eps, 0.0, 1.0)
    input_bounds = HyperRectangle(lower_bound, upper_bound)

    # Build sequential model for IBP propagation
    layers = [
        model.fc1, nn.ReLU(),
        model.fc2, nn.ReLU(),
        model.fc3, nn.ReLU(),
        model.fc4
    ]
    bound_model = nn.Sequential(*layers)

    # Construct bounded model and compute output bounds
    bounded_net = BoundModelFactory().build(bound_model)
    bounds = bounded_net.ibp(input_bounds)

    lower, upper = bounds.lower[0], bounds.upper[0]
    true_lower = lower[y]

    # Verify that all other classes’ upper bounds stay below the true label’s lower bound
    return not any(upper[i] >= true_lower for i in range(len(lower)) if i != y)

In [ ]:
def compute_verified_accuracy(model, loader, eps, device="cuda"):
    model.eval()
    verified = correct = 0

    for x, y in loader:
        x, y = x.to(device), y.to(device)

        with torch.no_grad():
            preds = model(x).argmax(dim=1)

        for i in range(len(x)):
            if preds[i].item() == y[i].item():
                correct += 1
                if verify_robustness_single_image(model, x[i:i+1], y[i].item(), eps):
                    verified += 1

    acc = 100.0 * verified / correct if correct > 0 else 0.0
    return verified, correct, acc

In [ ]:
epsilon_values = np.linspace(0.01, 0.1, 10)
verified_results = []

print("Verified Accuracy Evaluation (Box Verification)")

for eps in epsilon_values:
    num_verified, num_correct, verified_acc = compute_verified_accuracy(model, test_loader, eps, device=device)
    verified_results.append((eps, num_verified, num_correct, verified_acc))
    print(f"ε={eps:.3f} → Verified: {num_verified}/{num_correct} ({verified_acc:.2f}%)")

Verified Accuracy Evaluation (Box Verification)
ε=0.010 → Verified: 9519/9602 (99.14%)
ε=0.020 → Verified: 9419/9602 (98.09%)
ε=0.030 → Verified: 9323/9602 (97.09%)
ε=0.040 → Verified: 9196/9602 (95.77%)
ε=0.050 → Verified: 9041/9602 (94.16%)
ε=0.060 → Verified: 8877/9602 (92.45%)
ε=0.070 → Verified: 8664/9602 (90.23%)
ε=0.080 → Verified: 8419/9602 (87.68%)
ε=0.090 → Verified: 8164/9602 (85.02%)
ε=0.100 → Verified: 7764/9602 (80.86%)
