## Interval Analysis

In [6]:
# !pip install tensorboardX
# !pip install bound-propagation

from tqdm import tqdm
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import time
import matplotlib.pyplot as plt

from torchvision import datasets, transforms
# from tensorboardX import SummaryWriter

use_cuda = False
#device = torch.device("cuda" if use_cuda else "cpu")
device = torch.device("cpu")
batch_size = 64

np.random.seed(42)
torch.manual_seed(42)


## Dataloaders
train_dataset = datasets.MNIST('mnist_data/', train=True, download=True, transform=transforms.Compose(
    [transforms.ToTensor()]
))
test_dataset = datasets.MNIST('mnist_data/', train=False, download=True, transform=transforms.Compose(
    [transforms.ToTensor()]
))

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)
bound_test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=1, shuffle=False)

class Net(nn.Sequential):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(28*28, 50)
        self.fc2 = nn.Linear(50, 50)
        self.fc3 = nn.Linear(50, 50)
        self.out = nn.Linear(50, 10)

    def forward(self, x):
        x = x.view(-1, 28*28)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = self.out(x)
        return x


stan_model = Net().to(device)
stan_model.train()


Net(
  (fc1): Linear(in_features=784, out_features=50, bias=True)
  (fc2): Linear(in_features=50, out_features=50, bias=True)
  (fc3): Linear(in_features=50, out_features=50, bias=True)
  (out): Linear(in_features=50, out_features=10, bias=True)
)

In [ ]:
def train_model(model, num_epochs):
    model.to(device)
    optimizer = optim.SGD(model.parameters(), lr=0.01)

    for epoch in range(num_epochs):
        model.train()
        running_loss = 0.0
        for batch_idx, (images, labels) in tqdm(enumerate(train_loader), total=len(train_loader), desc=f"Epoch {epoch+1}/{num_epochs}"):
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            loss = F.cross_entropy(model(images), labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()

        print(f'Epoch {epoch+1}/{num_epochs}, Loss: {running_loss/len(train_loader):.3f}')

def test_model(model):
    model.eval()
    
    with torch.no_grad():
        correct = 0
        total = 0
        for data in test_loader:
            images, labels = data
            images = images.view((-1, 28*28))
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
        print(f'Accuracy on images: {100 * correct / total}')
    

In [5]:
startq = time.time()
train_model(stan_model, 20)
endq = time.time()

print(f"Standard Training Time: {endq - startq} seconds")

Epoch 1/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 3.5002e+00, -5.7343e+00,  4.9217e+00, -7.0153e+00,  2.8521e+00,
          1.1329e+00,  1.4782e+01, -6.1959e+00, -6.4175e-01, -7.8219e+00],
        [ 9.0531e+00, -5.7039e+00,  2.5185e+00, -9.2835e-01, -1.0883e+01,
          5.8338e+00, -4.4790e-01, -2.3707e+00,  3.6181e+00, -2.2712e+00],
        [-3.1649e+00,  6.1360e+00,  2.6338e+00, -1.2534e+00, -2.8729e+00,
          7.9285e-02,  1.8301e+00, -1.9887e-01,  3.6824e+00, -3.1582e+00],
        [ 5.9612e+00, -7.0752e+00, -2.7562e+00,  1.7988e+00, -6.5287e+00,
          1.2979e+01,  2.4008e+00, -1.0199e+01,  2.8304e+00, -9.6021e-01],
        [-7.5943e+00,  1.0102e+01,  3.3238e+00,  4.1009e+00, -4.0512e+00,
          7.1675e-01, -2.7406e+00,  5.1235e-01,  3.1200e+00, -2.7263e+00],
        [ 1.9243e+01, -9.6213e+00,  8.1646e+00, -6.2615e+00, -2.0324e+01,
          9.1186e+00,  3.9841e+00, -5.9167e+00,  5.6110e+00, -7.1844e+00],
        [-5.9295e+00, -4.6584e+00, -3.3157e+00,  6.2256e+00,  1.6278e+00,
          4.0748e+00, -1.3804e+0

Epoch 2/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-5.0182e+00, -6.1691e+00, -8.5722e+00, -2.8447e-01,  7.3501e+00,
          5.9552e+00, -5.6788e+00, -2.0422e+00,  8.3908e+00,  1.1224e+01],
        [ 1.4442e-01, -4.2998e+00, -6.6170e-01, -2.0361e+00,  1.9796e+00,
         -2.4480e+00, -5.1920e+00,  9.1833e+00,  1.5926e+00,  2.8965e+00],
        [ 1.3165e+00, -7.3567e+00,  1.2179e+01,  3.7444e+00,  3.0409e-01,
         -7.3817e+00,  4.2293e+00,  2.1595e+00, -2.7127e+00, -7.1006e+00],
        [-2.0347e+00,  2.7407e+00,  4.6049e+00,  1.2440e+01, -1.0991e+01,
          4.3417e+00, -5.4429e+00, -5.5856e+00,  6.0269e+00, -4.9450e+00],
        [-9.3489e+00,  1.1591e+01,  1.6804e+00,  2.6879e+00, -2.1451e+00,
         -1.7648e+00, -4.4272e+00,  3.9679e+00,  3.2944e+00,  3.9497e-01],
        [-6.8072e+00,  1.0182e+01,  8.8868e-01,  1.0388e+00, -2.9817e+00,
          2.1408e+00,  7.2668e-01, -9.8097e-01,  4.2432e+00, -3.3694e+00],
        [-6.9121e+00,  9.8430e+00,  2.8272e+00,  3.2276e+00, -3.9911e+00,
          1.2139e+00, -1.5149e+0

Epoch 3/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-7.8917e+00,  9.3859e+00,  2.9921e+00,  1.3203e+00, -1.2705e-01,
         -3.0751e+00, -1.2139e+00,  3.4093e+00,  1.8452e+00, -1.5269e+00],
        [-5.2503e+00,  2.3774e-01, -4.4339e+00,  1.9792e+00,  2.7190e+00,
          1.4242e+00, -8.3132e+00,  3.3498e+00,  1.8065e+00,  9.0457e+00],
        [ 6.6417e-01, -1.9099e+00,  4.1591e+00, -6.1775e+00,  3.3514e+00,
          6.0718e-01,  1.4120e+01, -4.6507e+00, -2.6757e-01, -8.5878e+00],
        [-2.5025e+00,  2.5427e+00,  5.7611e+00,  7.5253e-01, -3.1587e+00,
         -1.2286e+00, -1.1738e-01,  3.1042e-02,  2.7819e+00, -2.1799e+00],
        [-6.0506e+00,  7.3500e+00, -5.2910e-01, -2.7054e+00, -1.2069e+00,
          2.4157e+00,  1.5354e+00, -3.0183e+00,  8.5242e+00,  3.7609e-01],
        [ 2.1216e+00,  6.5730e+00,  1.2548e+01,  6.1420e+00, -1.9136e+01,
          3.1323e+00, -9.7804e-02, -5.0799e+00,  6.3461e+00, -1.0732e+01],
        [ 1.3670e+00, -2.2355e+00, -1.5916e+00,  5.4318e-01, -1.4847e+00,
          5.1745e+00, -4.6461e-0

Epoch 4/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[  1.0757,  -1.0213,   2.2045,  -6.2809,   0.5709,   1.0484,  10.5879,
          -4.5931,   3.1094,  -5.2857],
        [ -5.5091,   4.4436,  16.7899,   7.9705, -10.3044,  -9.0077,  -3.7774,
           4.2296,   7.2051,  -6.8607],
        [  3.3105,  -4.5877,   1.0733,   0.7699,  -1.2858,   4.1043,   6.8334,
          -6.5674,   0.3315,  -5.3970],
        [ -7.7967,   3.5321,  -0.8645,   4.0199,   2.0234,   1.9826,  -4.4745,
          -1.5740,   6.5527,   2.4459],
        [ -1.1533,  -8.2860,  -3.2065,  -4.8177,  11.9813,  -0.6850,   2.0704,
           0.1069,   1.9708,   4.8453],
        [ -6.4537,   4.6614,   1.9970,   2.2284,  -1.3822,   1.7712,   0.6592,
          -3.8968,   8.7907,  -2.8012],
        [ -0.6333,  -1.7829,   0.7121,   1.9769,  -4.9819,   1.1125, -10.4533,
           9.5271,   0.7706,   3.6504],
        [ -1.3697,  -4.1250,  -0.4355,  -3.0780,   6.9009,  -0.9901,   0.6873,
           1.8225,  -0.4915,   2.7801],
        [  3.6971,  -1.5042,   0.8331,   0.2600,

Epoch 5/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 5.0499e+00, -6.2305e+00,  1.2814e+01,  6.4939e+00, -1.4722e+01,
         -3.3747e+00, -1.1188e+01,  8.2607e+00,  2.3792e+00, -5.9074e-01],
        [-4.6420e-01, -5.7892e+00,  4.6942e-01, -2.9604e+00,  5.6572e+00,
         -4.3061e+00, -2.7576e+00,  8.4709e+00,  7.8324e-01,  2.5915e+00],
        [ 2.4895e-01, -4.6315e+00,  1.1727e+01,  5.4816e+00, -6.7855e+00,
         -6.3980e+00, -5.4466e+00,  3.2865e+00,  4.4774e+00, -7.6688e-01],
        [ 9.0011e+00, -7.1322e+00,  3.6710e+00, -1.1172e+00, -5.3298e+00,
          2.9806e-01,  2.3089e+00,  2.8851e-01, -5.9897e-01, -4.2591e+00],
        [ 4.7315e+00, -6.3739e+00,  3.6564e+00, -5.5871e+00, -1.7261e-01,
          1.2096e+00,  1.2876e+01, -7.4574e+00,  2.7387e+00, -6.0164e+00],
        [-1.2121e+00,  5.2472e+00,  1.0458e+01,  5.0061e+00, -1.1705e+01,
         -1.4148e+00, -3.6884e+00,  2.7298e+00,  2.9878e+00, -5.9190e+00],
        [-4.6134e+00, -2.5444e+00, -8.5152e-01, -3.5708e+00,  1.0553e+01,
         -2.4628e+00,  1.6772e+0

Epoch 6/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[  3.3754,  -3.3640,  -3.9975,   2.5602,  -6.9482,  13.0455,  -1.0879,
          -7.9727,   4.8964,   0.0330],
        [ -0.9058,   0.1527,   9.8611,   2.7669,  -5.3736,  -4.4763,  -2.2708,
           4.7976,   1.5563,  -3.9815],
        [ -6.7910,   9.0962,  -0.1521,   2.2607,  -1.8130,   1.5573,  -2.0610,
           0.2088,   2.5823,  -0.6272],
        [ -2.0008,  -1.9814,   1.0827,  -2.5983,   1.9178,  -2.5225,   2.9431,
          -0.5343,   9.5189,  -0.4528],
        [ -1.3416,  -7.5679,  -1.4342,  -0.2348,   4.2975,  -2.4846,  -9.5025,
           8.4762,   1.8698,   9.4331],
        [  1.9611,  -6.7701,   0.2551,  -4.4056,   3.7963,  -5.2178,  -1.1647,
           9.2065,   1.4117,   1.7559],
        [  1.9298,  -0.2899,   2.2270,  -4.0070,  -1.1962,   3.5284,  10.3851,
          -5.3611,   0.4496,  -7.5639],
        [  9.5843,  -3.7811,   5.2100,  -5.9452,  -8.4752,   1.1010,   4.2342,
          -0.1210,   3.2010,  -5.4173],
        [  0.6659,  -7.0652,  11.8591,   2.5664,

Epoch 7/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 4.9643e-01, -3.0591e+00,  7.1965e+00,  6.4563e+00, -9.3016e+00,
          3.8633e+00,  3.3846e+00, -1.1309e+01,  1.1907e+01, -6.5893e+00],
        [-2.4510e+00, -3.3058e+00,  2.7453e+00,  6.0260e+00, -9.7336e+00,
         -2.3158e+00, -2.1835e+01,  1.6362e+01,  5.5932e+00,  1.0401e+01],
        [-7.0667e-01,  1.9736e+00,  1.2738e-01, -1.9433e+00, -6.3960e-01,
          3.0750e+00,  5.5978e+00, -3.3572e+00,  1.1596e+00, -4.1923e+00],
        [-7.6380e+00,  9.1620e+00,  3.2009e+00,  1.1164e+00, -5.7930e-01,
         -3.1057e+00, -2.0935e+00,  3.8663e+00,  1.7764e+00, -6.4629e-01],
        [-7.4051e+00,  8.7734e+00,  4.4440e+00,  2.0644e+00, -1.4242e+00,
         -3.8124e+00, -2.3805e+00,  4.1879e+00,  1.8354e+00, -1.4507e+00],
        [-3.8007e+00, -8.6902e+00, -3.3035e+00,  1.7722e+00,  6.1010e+00,
         -1.0933e+00, -9.6756e+00,  3.1201e+00,  6.1369e+00,  1.2623e+01],
        [ 5.9420e+00, -5.4652e+00,  5.1704e+00, -6.1608e+00, -3.7369e+00,
         -4.6268e-01,  1.0035e+0

Epoch 8/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 2.9670e+00, -1.5560e+00, -3.1437e-01,  3.9952e+00, -9.5129e+00,
          1.0866e+01, -6.9322e-01, -7.6218e+00,  4.6761e+00, -2.3069e+00],
        [-5.8633e+00,  5.2492e+00, -9.0149e-01,  2.5489e+00, -2.6506e+00,
          1.1092e+00, -4.0831e+00, -4.9524e-01,  9.8285e+00,  1.3653e+00],
        [ 3.6507e-01, -2.2085e+00,  3.2651e+00, -5.0690e+00,  2.5783e+00,
          2.7355e+00,  1.1619e+01, -6.0931e+00,  7.8635e-01, -7.0376e+00],
        [-7.2410e+00,  1.0403e+01,  1.3727e+00, -2.7239e+00,  1.7311e-01,
         -1.9623e-01,  4.6856e+00,  2.3576e-01,  2.8360e+00, -3.8821e+00],
        [-1.6034e+00, -6.7469e+00, -3.7669e+00,  1.5776e-02,  5.6626e+00,
          2.2587e+00, -5.6210e+00,  2.0831e+00,  7.2586e-01,  8.4416e+00],
        [-3.6407e+00, -4.4091e+00, -2.3906e+00, -3.6712e+00,  1.0648e+01,
         -1.5973e+00,  1.7165e-01,  2.2830e+00,  1.9947e+00,  4.3305e+00],
        [-4.6957e+00,  7.0544e+00,  3.7551e-01,  8.6240e-01, -2.2137e+00,
          2.5526e+00,  4.5183e-0

Epoch 9/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ 3.3923e+00, -7.9453e+00, -1.3962e+00, -3.6317e+00,  2.7376e+00,
         -1.4246e+00, -5.4241e-01,  6.1428e+00, -9.5066e-02,  2.1713e+00],
        [ 1.8785e+01, -9.4878e+00,  5.9797e+00, -7.6467e+00, -1.6317e+01,
          1.1143e+01,  6.8992e+00, -7.0236e+00,  2.1039e+00, -8.2293e+00],
        [-4.1634e+00,  2.6226e+00,  5.3547e+00,  1.3415e+01, -8.7852e+00,
          6.8135e-01, -7.4303e+00, -2.1537e+00,  4.7816e+00, -3.1373e+00],
        [-1.7332e+00, -3.3596e+00,  2.7216e+00, -2.9949e+00,  6.5859e+00,
         -2.9393e+00,  4.3220e+00,  1.4722e+00, -1.9822e-01, -1.2312e+00],
        [-2.7842e+00,  1.6528e+00,  8.0633e-01,  5.4245e+00, -7.9595e+00,
          5.7699e+00, -6.2212e+00, -5.5839e+00,  1.2316e+01,  1.4149e+00],
        [ 1.4185e+01, -1.4138e+01,  2.9757e+00, -7.7051e+00, -3.7859e+00,
         -3.8720e-01,  5.9032e+00, -1.1148e+00,  2.9729e+00, -1.3316e+00],
        [-7.4003e+00,  9.6555e+00, -3.2026e-01, -1.3247e+00,  6.2764e-01,
          3.4056e-02,  2.3718e+0

Epoch 10/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-2.2588e+00, -4.1309e+00, -3.0355e+00, -8.1254e-01,  6.3548e+00,
          9.7981e-01, -1.6501e+00,  6.2555e-02,  1.1842e+00,  5.1954e+00],
        [-4.2269e-01, -6.7172e+00,  8.8494e+00,  3.6765e+00,  7.9570e-01,
         -2.7204e+00, -3.2647e+00,  2.4721e+00, -7.6112e-01, -4.4021e-01],
        [ 1.6971e+00, -2.6153e+00,  2.5533e+00, -5.7714e+00,  3.1049e+00,
          1.4611e-01,  1.1129e+01, -2.2488e+00, -1.8403e+00, -5.9052e+00],
        [-4.2346e+00, -2.4326e+00, -3.5355e+00,  1.0146e+00,  4.9713e+00,
          2.4280e+00, -4.8346e+00, -4.3806e-01,  1.8270e+00,  7.6980e+00],
        [-6.1756e+00,  1.1085e+00, -1.5411e+00, -2.5671e-01,  5.0277e+00,
         -1.9903e+00, -5.5026e+00,  4.6636e+00,  2.5830e+00,  6.5020e+00],
        [ 2.5075e+00, -6.4049e+00,  3.8557e+00,  4.9704e+00, -9.1640e+00,
          4.7016e+00, -6.3444e+00, -5.8503e+00,  1.1326e+01,  2.8534e+00],
        [ 7.1387e+00, -1.2641e+01,  6.9065e+00, -9.5963e+00,  4.8688e+00,
         -5.2943e+00,  1.4424e+0

Epoch 11/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-5.1061e+00,  6.9499e+00,  1.5608e-01, -2.3838e+00, -1.5437e+00,
          8.0828e-01,  3.6455e+00, -2.5397e+00,  7.2341e+00, -1.9399e+00],
        [ 1.4617e+00, -4.2126e+00,  5.8458e+00,  2.3879e+00, -9.2690e+00,
          4.5035e-02, -6.7601e+00, -1.1936e+00,  1.5879e+01,  1.4839e+00],
        [-1.5713e+00, -4.3380e+00, -3.1683e+00,  5.7132e-01,  2.3080e+00,
          2.4273e+00, -9.1952e+00,  7.8026e+00,  1.8128e+00,  5.4674e+00],
        [-5.2764e+00, -1.9637e+00,  5.3244e-01,  4.5872e+00,  3.4365e-01,
          2.2310e+00, -1.1614e+01,  2.5701e+00,  2.5171e+00,  9.2052e+00],
        [-3.4744e-01, -2.2954e+00, -2.9876e-01,  1.2222e+01, -7.7959e+00,
          7.6253e+00, -7.4126e+00, -4.0404e+00,  5.2905e-02, -4.4536e-01],
        [ 3.1991e+00, -3.5800e+00,  3.3748e+00, -5.7266e+00,  1.3724e+00,
          1.8629e-02,  1.3258e+01, -4.5334e+00, -4.8708e-01, -7.3923e+00],
        [-6.4209e+00,  1.0042e+01,  3.2926e+00, -2.7501e-01, -3.1841e+00,
         -1.3135e+00,  1.7532e-0

Epoch 12/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ -1.2809,  -9.2276,  -3.5768,   0.8376,   3.4818,   1.9144,  -9.6974,
           4.0387,   3.4675,  11.7189],
        [ -4.3295,   3.6893,   2.3155,   8.6747,  -5.7940,   0.8235,  -6.7544,
          -0.2668,   3.1533,  -0.0601],
        [ -2.7748,   5.9241,   1.3327,  -1.7237,  -3.8399,   1.2440,   1.8199,
          -1.0319,   6.7635,  -2.9663],
        [ -0.0365,  -0.9887,   7.9608,   3.5093,  -3.5145,  -1.9561,   3.0104,
          -1.7510,  -0.1406,  -6.1438],
        [ -1.5219,   0.0584,   8.3961,  16.9668, -18.2428,   2.4907, -18.8621,
           4.7590,   5.0833,   0.6545],
        [ -2.7256,   1.7649,   3.4002,  10.8187,  -8.8188,   2.6652,  -7.1612,
          -1.8609,   3.5445,  -1.2716],
        [ -4.1209,  -5.4217,  -1.0778,   3.3826,   2.0979,  -0.3446, -12.1526,
           4.8488,   5.2439,  10.8008],
        [  1.7344,  -3.8610,  -4.5763,   3.9050,  -2.7207,  12.1852,  -0.0998,
          -6.6664,  -0.6476,  -0.9180],
        [ -0.9956,  -0.7540,   2.8079,   2.3966,

Epoch 13/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-8.4852e+00,  1.0007e+01, -5.6482e-01, -5.0807e-01,  6.8876e-01,
         -7.9426e-01,  3.7583e-01,  1.1443e+00,  5.6302e+00, -5.9001e-01],
        [-2.8676e+00,  3.2010e+00,  1.3430e+01,  3.5712e+00, -7.5459e+00,
         -4.6072e+00, -7.8262e-01,  1.0121e+00,  3.5058e+00, -5.4055e+00],
        [ 9.9901e-01, -1.1896e+00,  5.1443e+00, -6.9356e+00,  1.9439e+00,
         -1.5124e+00,  1.6584e+01, -4.7932e+00,  1.2984e+00, -1.0257e+01],
        [-6.0840e+00,  9.7044e+00,  2.8650e+00, -1.2357e+00, -2.0595e+00,
         -7.3656e-01,  1.8465e+00,  8.9477e-01,  3.5603e+00, -3.3992e+00],
        [-7.8025e-01, -4.2064e+00,  6.4808e+00,  3.4293e+00, -2.5607e+00,
         -3.5695e+00, -1.0206e+01,  9.4542e+00,  1.7439e+00,  2.1388e+00],
        [-5.0568e+00, -5.2854e+00,  5.3424e-01,  5.4239e+00,  1.0244e+00,
         -1.8690e+00, -1.5715e+01,  7.1426e+00,  5.5746e+00,  1.1872e+01],
        [-7.5980e+00,  8.1079e+00,  2.2636e+00,  2.1980e+00, -1.5664e-01,
         -2.6914e+00, -4.2310e+0

Epoch 14/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-1.8305e+00,  2.3632e+00,  2.2171e+00,  3.2914e+00, -1.0245e+01,
          1.5890e+00, -7.1424e+00, -8.9200e-01,  1.4716e+01,  1.7752e+00],
        [-5.2783e+00,  5.2964e+00, -9.9060e-01, -3.8203e-01,  1.8854e+00,
         -5.8054e-01, -1.8284e+00,  2.6809e+00,  5.2036e-01,  2.1156e+00],
        [-2.8293e-01, -6.9456e+00,  1.4647e+00,  1.7761e+00, -1.5833e+00,
          9.8628e-02, -1.1586e+01,  7.6065e+00,  2.0404e+00,  8.1067e+00],
        [-4.5005e+00,  8.5353e+00,  4.1574e+00, -7.3518e-01, -4.2579e+00,
         -4.7933e-01,  2.6962e+00,  2.6034e-01,  3.7678e+00, -5.0214e+00],
        [-3.2224e+00,  2.3665e+00,  1.0577e+01,  8.8793e+00, -1.0104e+01,
         -3.4537e+00, -1.0892e+01,  5.9411e+00,  3.7970e+00, -1.1941e+00],
        [-1.5337e+00,  6.8802e+00,  9.7551e+00,  5.1850e+00, -1.3651e+01,
          2.3407e-01, -5.6457e+00,  2.0331e+00,  5.8381e+00, -5.2361e+00],
        [ 5.2246e+00, -3.9834e+00,  5.6307e-01, -6.1298e+00, -1.6066e+00,
          4.8256e+00,  8.5319e+0

Epoch 15/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-1.3564e+00, -7.3245e-01,  2.0559e+00,  1.0898e+01, -1.2555e+01,
          6.2766e+00, -1.3219e+01, -1.3565e+00,  7.1195e+00,  3.8276e+00],
        [-2.7759e+00,  4.2977e+00,  2.6783e+00,  1.2114e+01, -1.3212e+01,
          6.8461e+00, -8.6469e+00, -3.8084e+00,  5.6953e+00, -2.0336e+00],
        [ 1.4483e+00, -1.2023e+00, -2.2198e+00,  1.0302e+00, -2.3327e+00,
          9.1319e+00,  8.4900e-01, -4.5029e+00,  3.2558e-01, -2.5153e+00],
        [-3.3185e+00, -5.5569e+00, -2.4685e+00, -4.3548e+00,  1.2031e+01,
         -2.0348e+00,  1.5692e+00,  1.9289e+00,  1.0853e+00,  4.4588e+00],
        [ 4.5117e+00, -7.0637e+00, -3.0159e+00,  6.5110e+00, -1.0880e+01,
          1.6052e+01, -7.3921e+00, -6.3560e+00,  1.7895e+00,  3.4155e+00],
        [ 1.5442e+01, -1.1926e+01,  4.7040e+00, -4.3260e+00, -1.2735e+01,
          5.5557e+00, -8.4543e-02, -8.1355e-01,  3.1712e+00, -2.0120e+00],
        [-1.6022e+00, -3.5698e+00, -1.0565e+00,  2.0450e+00, -6.2552e+00,
          2.9963e+00, -9.6047e+0

Epoch 16/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[ -2.1053,  -2.2003,  11.7098,  16.7827, -18.5082,  -0.6415, -21.6771,
           5.1108,  10.8631,   3.4771],
        [ -6.9538,   8.6751,   1.4307,   0.8970,  -0.6108,  -1.7564,  -1.8064,
           2.9551,   1.9912,  -0.2930],
        [ -2.3499,   0.2765,  -1.7904,   9.8747,  -6.0271,   7.6783,  -7.4138,
          -3.7275,   1.1252,   1.4758],
        [ -2.3241,  -1.0198,  -0.5591,   0.8975,  -0.2735,   0.8831,  -0.7432,
          -2.6571,   8.4480,   1.2403],
        [  3.2806,  -4.5879,   4.4371,  -4.7767,   0.3304,   0.5563,  15.1138,
          -7.4243,   1.8292,  -8.9923],
        [  1.0725,  -5.9831,  11.4202,   2.7596,  -2.9090,  -6.7335,  -0.4618,
           2.2445,   1.4186,  -2.3846],
        [ -0.7274,   0.1951,   3.1938,  -5.7888,   3.6608,   0.2467,  11.2841,
          -2.2167,  -1.2985,  -7.1365],
        [ -7.6987,  10.0880,   1.8985,   2.8965,  -2.4450,  -1.3440,  -2.4814,
           2.1088,   3.1507,  -1.3232],
        [ -5.7017,   8.3034,   2.1911,  -0.8417,

Epoch 17/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-4.8279e+00,  7.9360e+00,  3.3966e+00, -1.8272e-01, -3.2059e+00,
         -1.2550e+00,  1.2132e+00,  8.3643e-01,  4.1452e+00, -3.3700e+00],
        [ 7.2694e-01, -2.2886e+00,  6.2333e+00, -4.7991e+00,  2.8102e+00,
         -2.8035e+00,  1.3072e+01, -2.3527e+00, -1.0930e+00, -8.6282e+00],
        [-2.7216e+00,  8.6097e+00,  1.4490e+01,  1.1702e+01, -1.8751e+01,
          2.6589e-01, -7.8595e+00,  2.5601e+00,  4.0767e+00, -9.6556e+00],
        [ 3.9148e+00, -9.1987e-01,  1.9897e+00, -3.7921e+00, -7.4912e+00,
          4.7265e+00,  3.2028e+00, -5.8768e+00,  1.0741e+01, -2.7136e+00],
        [ 2.0649e+00, -3.0460e+00,  2.2449e+00, -2.5517e+00,  1.0533e+00,
          1.0906e+00,  1.0143e+01, -4.2193e+00, -5.4168e-02, -6.9136e+00],
        [ 3.1933e+00, -5.4095e+00,  8.2979e+00, -8.1394e+00,  3.8487e+00,
         -2.6120e+00,  1.6984e+01, -3.5243e+00, -2.1586e+00, -1.0097e+01],
        [-3.4168e+00,  1.4820e+00,  1.5418e+01,  6.4961e+00, -8.1009e+00,
         -5.8825e+00, -3.5811e+0

Epoch 18/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-9.1845e+00,  8.8279e+00,  2.3051e+00,  3.4496e+00, -1.7609e-01,
         -2.7272e+00, -4.9299e+00,  3.4433e+00,  4.2642e+00,  1.0025e+00],
        [ 5.6608e-01, -4.3052e+00,  6.5757e+00,  3.6730e+00, -5.7167e+00,
         -4.2980e+00, -1.0802e+01,  1.2122e+01, -4.0897e-01,  1.8917e+00],
        [-1.4482e+00, -1.9970e+00, -1.4549e+00,  9.9150e+00, -1.2886e+01,
          8.3127e+00, -1.8146e+01,  4.0663e+00,  5.5719e+00,  8.2908e+00],
        [-8.7360e-01, -1.1008e+01, -1.2330e+00,  1.8946e+00,  4.1198e+00,
          2.5097e+00, -9.6235e+00,  1.1960e+00,  3.0104e+00,  1.1743e+01],
        [ 4.2359e+00, -7.1926e+00,  4.9556e+00, -9.5447e+00,  4.5817e+00,
         -1.6854e+00,  1.5936e+01, -4.4762e+00,  2.4906e-01, -6.6331e+00],
        [-8.0090e-02, -1.8186e+00, -3.2235e-01,  3.7963e-01, -2.5219e+00,
          8.8670e+00,  8.9968e-02, -7.6133e+00,  5.3536e+00,  6.7551e-02],
        [ 1.7833e+00, -3.1494e+00, -1.1003e+00,  1.0219e+00, -2.0233e+00,
          3.2178e+00, -2.6041e+0

Epoch 19/20:   0%|          | 0/938 [00:00<?, ?it/s]


tensor([[-5.9967e+00,  7.5221e+00,  1.1533e+00,  1.5237e+00, -1.0194e+00,
         -1.0983e+00, -2.1442e+00,  2.4331e+00,  1.7347e+00, -3.8107e-01],
        [ 7.3266e-01,  3.1762e-02, -2.2480e+00,  1.6032e+00, -3.2224e+00,
          9.0613e+00, -4.8928e-01, -3.7350e+00,  6.2364e-01, -1.9878e+00],
        [ 3.4882e+00, -5.1686e+00,  2.5412e+00, -5.7838e+00,  1.8977e+00,
          2.5427e+00,  1.3555e+01, -6.9264e+00,  6.3400e-01, -7.1519e+00],
        [-1.0617e+00, -1.8717e+00,  2.4825e-02,  8.8396e+00, -5.5488e+00,
          4.6766e+00, -7.8944e+00, -5.9120e-01,  2.4457e-01,  1.5320e+00],
        [-9.4025e-01, -4.4733e+00, -1.1364e+00, -1.3712e+00,  5.5701e+00,
          2.2670e-01,  3.6914e-01, -2.4944e-01,  6.4711e-01,  2.7030e+00],
        [-2.8646e+00, -6.1472e+00, -2.5558e+00, -2.8748e+00,  1.1431e+01,
          2.3336e-01,  5.9271e-01,  1.1449e-01, -5.3506e-02,  4.9260e+00],
        [-4.0228e+00, -2.6162e+00, -1.4798e+00, -4.2951e-01,  7.6027e+00,
         -5.3280e-01,  7.8132e-0

Epoch 20/20:   0%|          | 0/938 [00:00<?, ?it/s]

tensor([[-5.0166e+00, -4.4431e+00, -4.7324e+00,  4.6374e+00,  2.1556e+00,
          1.3717e+00, -1.2486e+01,  3.5181e+00,  4.6396e+00,  1.2766e+01],
        [ 2.3661e+00, -4.2028e+00,  6.1463e+00, -7.4028e+00,  4.1042e+00,
         -5.9757e-01,  1.5524e+01, -3.8925e+00, -2.5267e+00, -9.0084e+00],
        [ 1.1883e+00,  1.3312e+00,  4.8093e+00, -2.4536e+00, -3.1505e+00,
          2.9755e+00,  1.0928e+01, -5.4234e+00,  1.1339e-01, -1.0075e+01],
        [ 3.3619e+00,  2.9867e-01,  7.2697e-01,  6.0110e-01, -9.2667e+00,
          1.0733e+01,  1.3457e+00, -7.3440e+00,  2.7867e+00, -3.3455e+00],
        [-2.4388e+00,  3.2962e-01,  1.2728e+01,  4.9048e+00, -7.3818e+00,
         -4.4657e+00, -3.7025e+00,  6.8817e-01,  4.9681e+00, -2.2511e+00],
        [-4.7714e+00, -5.0246e+00, -1.6813e+00, -2.7095e+00,  1.0967e+01,
         -1.8610e-01, -7.7679e-01,  8.3188e-01,  1.5719e+00,  6.0364e+00],
        [-5.2315e+00, -2.3498e+00, -5.3660e+00, -2.9185e+00,  1.0930e+01,
          8.5470e-01,  3.5562e-0

In [8]:
test_model(stan_model)

Accuracy on images: 96.7


In [9]:
from bound_propagation import BoundModelFactory, HyperRectangle
def rb_worst(model, x, y, eps):
    x = x.view(-1, 28*28)
    L = torch.clamp(x - eps, 0, 1)
    U = torch.clamp(x + eps, 0, 1)
    factory = BoundModelFactory()
    box = HyperRectangle(L, U)

    alter = nn.Sequential(
        model.fc1,
        nn.ReLU(),
        model.fc2,
        nn.ReLU(),
        model.fc3,
        nn.ReLU(),
        model.out   
    )

    bound_net = factory.build(alter)
    interval = bound_net.ibp(box)
    lower, higher = interval.lower, interval.upper
    mask = torch.ones_like(lower, dtype=torch.bool)
    for i in range(x.size(0)):
        mask[i, y[i]] = False
    res = torch.where(mask, higher, lower)
    loss = F.cross_entropy(res, y)
    return loss

In [10]:
def train_model_ibp(model, num_epochs):
    optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.9)

    for epoch in range(num_epochs):
        model.train()
        kappa = 1.0 - 0.5 * (epoch / num_epochs)
        eps = 0.1 * epoch / num_epochs
        for batch_idx, (images, labels) in tqdm(enumerate(train_loader), total=len(train_loader), desc=f"Epoch {epoch+1}/{num_epochs}"):
            images = images.view((-1, 28*28))
            images, labels = images.to(device), labels.to(device)
            
            optimizer.zero_grad()
            logits = model(images)
            ce_loss = F.cross_entropy(logits, labels)
            rb_loss = rb_worst(model, images, labels, eps)
            loss = kappa * ce_loss + (1 - kappa) * rb_loss
            loss.backward()
            optimizer.step()
        model.eval()
        tot_val, tot_acc = 0.0, 0.0
        val_loss = 0.0
        for batch_idx, (images, labels) in enumerate(train_loader):
            images = images.view((-1, 28*28))
            images, labels = images.to(device), labels.to(device)
            with torch.no_grad():
                logits = model(images)
                ce_loss = F.cross_entropy(logits, labels)
                rb_loss = rb_worst(model, images, labels, eps)
                loss = kappa * ce_loss + (1 - kappa) * rb_loss
                val_loss += loss.item()
                tot_acc += (logits.argmax(dim=1) == labels).sum().item()
                tot_val += labels.size(0)
        val_acc = 100.0 * tot_acc / tot_val

        print(f'Epoch {epoch+1}/{num_epochs}, Loss: {val_loss/len(train_loader):.3f}, Accuracy: {val_acc:.2f}%')

In [11]:
ibp_model = Net().to(device)
ibp_model.train()
start = time.time()
train_model_ibp(ibp_model, 15)
end = time.time()

print(f"IBP Training Time: {end - start} seconds")


Epoch 1/15: 100%|██████████| 938/938 [00:04<00:00, 209.65it/s]


Epoch 1/15, Loss: 0.558, Accuracy: 83.54%


Epoch 2/15: 100%|██████████| 938/938 [00:04<00:00, 214.67it/s]


Epoch 2/15, Loss: 0.455, Accuracy: 89.54%


Epoch 3/15: 100%|██████████| 938/938 [00:04<00:00, 214.93it/s]


Epoch 3/15, Loss: 0.488, Accuracy: 90.91%


Epoch 4/15: 100%|██████████| 938/938 [00:04<00:00, 216.44it/s]


Epoch 4/15, Loss: 0.509, Accuracy: 91.87%


Epoch 5/15: 100%|██████████| 938/938 [00:04<00:00, 214.83it/s]


Epoch 5/15, Loss: 0.531, Accuracy: 92.73%


Epoch 6/15: 100%|██████████| 938/938 [00:04<00:00, 213.51it/s]


Epoch 6/15, Loss: 0.567, Accuracy: 93.66%


Epoch 7/15: 100%|██████████| 938/938 [00:04<00:00, 215.95it/s]


Epoch 7/15, Loss: 0.613, Accuracy: 94.21%


Epoch 8/15: 100%|██████████| 938/938 [00:04<00:00, 215.22it/s]


Epoch 8/15, Loss: 0.660, Accuracy: 94.53%


Epoch 9/15: 100%|██████████| 938/938 [00:04<00:00, 212.12it/s]


Epoch 9/15, Loss: 0.704, Accuracy: 94.96%


Epoch 10/15: 100%|██████████| 938/938 [00:04<00:00, 214.21it/s]


Epoch 10/15, Loss: 0.749, Accuracy: 95.29%


Epoch 11/15: 100%|██████████| 938/938 [00:04<00:00, 216.85it/s]


Epoch 11/15, Loss: 0.798, Accuracy: 95.38%


Epoch 12/15: 100%|██████████| 938/938 [00:04<00:00, 214.86it/s]


Epoch 12/15, Loss: 0.843, Accuracy: 95.62%


Epoch 13/15: 100%|██████████| 938/938 [00:04<00:00, 215.02it/s]


Epoch 13/15, Loss: 0.891, Accuracy: 95.63%


Epoch 14/15: 100%|██████████| 938/938 [00:04<00:00, 216.44it/s]


Epoch 14/15, Loss: 0.937, Accuracy: 95.68%


Epoch 15/15: 100%|██████████| 938/938 [00:04<00:00, 215.52it/s]


Epoch 15/15, Loss: 0.986, Accuracy: 95.80%
IBP Training Time: 110.66348099708557 seconds


In [13]:
def pgd(model, x, labels, k=40, eps=8/255, eps_step=0.001):
    model.eval()
    ce_loss = F.cross_entropy
    adv_x = x.clone().detach()
    adv_x = torch.clamp(adv_x, 0.0, 1.0)
    for _ in range(k):
        adv_x.requires_grad_(True)
        model.zero_grad()
        logits = model(adv_x)
        # TODO: Calculate the loss
        loss = ce_loss(logits, labels)
        loss.backward()
        assert adv_x.grad is not None
        grad = adv_x.grad.data
        # TODO: compute the adv_x
        adv_x = adv_x.detach() + eps_step * torch.sign(grad)
        adv_x = torch.clamp(adv_x, x - eps, x + eps)
        adv_x = torch.clamp(adv_x, 0, 1).detach()
    return adv_x

def evaluate_pgd(model):
    model.eval()
    tot_acc = 0.0
    tot_test = 0.0
    tot_acc_adv = 0.0
    for batch_idx, (images, labels) in enumerate(test_loader):
        images = images.to(device)
        labels = labels.to(device)
        images = images.view(-1, 28*28)
        adv_images = pgd(model, images, labels)
        outputs = model(adv_images)
        tot_acc_adv += (outputs.argmax(dim=1) == labels).sum().item()
        tot_test += labels.size(0)
        tot_acc += (model(images).argmax(dim=1) == labels).sum().item()
    return 100.0 * tot_acc / tot_test, 100.0 * tot_acc_adv / tot_test

stan_acc, stan_acc_adv = evaluate_pgd(stan_model)
print(f'Standard Model - Clean Accuracy: {stan_acc:.2f}%, PGD Accuracy: {stan_acc_adv:.2f}%')
ibp_acc, ibp_acc_adv = evaluate_pgd(ibp_model)
print(f'IBP Model - Clean Accuracy: {ibp_acc:.2f}%, PGD Accuracy: {ibp_acc_adv:.2f}%')


Standard Model - Clean Accuracy: 96.70%, PGD Accuracy: 81.87%
IBP Model - Clean Accuracy: 95.26%, PGD Accuracy: 80.39%


### Write the interval analysis for the simple model

In [ ]:
## TODO: Write the interval analysis for the simple model
## you can use https://github.com/Zinoex/bound_propagation

from bound_propagation import BoundModelFactory, HyperRectangle

factory = BoundModelFactory()
isinstance(stan_model, nn.Sequential)
net = factory.build(stan_model)

In [ ]:
net.eval()
epsilons = np.linspace(0.01, 0.1, 10)
always_correct = np.zeros(len(epsilons), dtype=int)
still_correct = np.zeros(len(epsilons), dtype=int)
correct = 0
total = 0

for images, labels in test_loader:
    images = images.view((-1, 28 * 28)).to(device)
    labels = labels.to(device)

    outputs = stan_model(images)
    _, predicted = torch.max(outputs.data, 1)
    predicted_correct = predicted == labels

    total += labels.size(0)
    correct += predicted_correct.sum().item()

    for idx, epsilon in enumerate(epsilons):
        input_bounds = HyperRectangle.from_eps(images, float(epsilon))
        crown_ibp_bounds = net.crown_ibp(input_bounds).concretize()
        lower, upper = crown_ibp_bounds.lower, crown_ibp_bounds.upper

        label_lower = lower.gather(1, labels.unsqueeze(1)).squeeze(1)
        label_mask = torch.zeros_like(upper, dtype=torch.bool)
        label_mask.scatter_(1, labels.unsqueeze(1), True)
        max_other_upper = upper.masked_fill(label_mask, float('-inf')).max(dim=1).values
        robust_mask = label_lower > max_other_upper
        always_correct[idx] += robust_mask.sum().item()

print(f'Standard accuracy: {correct / total*100:.2f}%')
for eps, ac in zip(epsilons, always_correct):
    print(f'eps={eps:.3f}: always_correct={ac / total * 100:.2f}%')

        
        
        
        
    


Standard accuracy: 96.70%
eps=0.010: always_correct=42.67%
eps=0.020: always_correct=18.58%
eps=0.030: always_correct=5.53%
eps=0.040: always_correct=1.23%
eps=0.050: always_correct=0.27%
eps=0.060: always_correct=0.08%
eps=0.070: always_correct=0.03%
eps=0.080: always_correct=0.00%
eps=0.090: always_correct=0.00%
eps=0.100: always_correct=0.00%
